Class {
	#name : #FiStoreBrowserPlugin,
	#superclass : #Object,
	#category : #'FicusStore-UI'
}

{ #category : #accessing }
FiStoreBrowserPlugin >> prepareDescriptionMorphs: morphs for: aHistoryNode [

]

{ #category : #accessing }
FiStoreBrowserPlugin >> prepareEffectInspectorTreeMorphs: morphs for: aSummary [

]

{ #category : #accessing }
FiStoreBrowserPlugin >> selectedHistoryNode: aHistoryNode [
]
